Improve the error message when run without `id-token: write` permission

diff --git a/action.yaml b/action.yaml
--- a/action.yaml
+++ b/action.yaml
@@ -51,6 +51,14 @@ runs:
           echo "$resp"
         }
 
+        if [[ ! -v ACTIONS_ID_TOKEN_REQUEST_TOKEN ]]
+        then
+          message='No $ACTIONS_ID_TOKEN_REQUEST_TOKEN is set. Does this job have the `id-token: write` permission necessary to get a Cloudsmith token?'
+          echo "$message" >&2
+          echo '::error title=Missing `id-token: write` permission?::'"$message"
+          exit 1
+        fi
+
         CLOUDSMITH_ACCOUNT=${CLOUDSMITH_ACCOUNT:-$GITHUB_REPOSITORY_OWNER}
         echo "Retrieving actions OIDC token"
         id_token=$(request -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=api://AzureADTokenExchange" | jq -r '.value')
